name: Lobbysystem
version: 0.1
api: 3.0.0
main: codingschule\Lobbysystem\Main
author:
  - Wildboy
  - ceepkev77
  - Firebro
commands:
  spawn:
    description: Teleportiert dich zum Spawn der Lobby
    usage: /spawn
    aliases: ["hub","lobby"]
  admin:
    description: Für Admins | /admin - öffnet UI  /admin help
    usage: /admin
    permission: admin.use
